#!/usr/bin/env bash

## Author  : Aditya Shakya
## Mail    : adi1090x@gmail.com
## Github  : @adi1090x
## Twitter : @adi1090x

export ROFITHEMES=$HOME/.config/rofi/themes/modules

dir="$ROFITHEMES"
uptime=$(uptime -p | sed -e 's/up //g')

rofi_command="rofi"

# Options
shutdown=" Shutdown"
reboot=" Reboot"
lock=" Lock"
suspend=" Sleep"
logout=" Logout"

# Variable passed to rofi
options="$shutdown\n$reboot\n$suspend\n$lock\n$logout"

chosen="$(echo -e "$options" | $rofi_command -p ": $uptime" -dmenu)"
case $chosen in
  $shutdown) systemctl poweroff ;;
  $reboot) systemctl reboot ;;
  $lock) i3lock ;;
  $suspend)
    mpc -q pause
		amixer set Master mute
		systemctl suspend
    ;;
  $logout)
    if [[ "$DESKTOP_SESSION" == "Openbox" ]]; then
      openbox --exit
    elif [[ "$DESKTOP_SESSION" == "bspwm" ]]; then
      bspc quit
    elif [[ "$DESKTOP_SESSION" == "i3" ]]; then
      i3-msg exit
    fi
    ;;
esac
